services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    ports:
      - "8545:8545"
    entrypoint: ["anvil"]
    command:
      - -vvvvv
      - --steps-tracing
      - --state
      - "/tmp/state.json"
      - -b
      - "10"
      - --host
      - 0.0.0.0
